// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"demo/microservice/user/rpc/types/app"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserReply = app.GetUserReply
	GetUserReq   = app.GetUserReq

	User interface {
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserReply, error) {
	client := app.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
