// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"demo/microservice/user/rpc/internal/logic"
	"demo/microservice/user/rpc/internal/svc"
	"demo/microservice/user/rpc/types/app"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	app.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *app.GetUserReq) (*app.GetUserReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
